name: Issue Notification
on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.EMAIL_USER}}
        password: ${{secrets.EMAIL_PASS}}
        subject: New Estimate Request
        body: A new estimate request has been submitted. Please check the GitHub issue for details.
        to: your-email@example.com
        from: GitHub Actions
